"""Draft Reply Engine endpoints: list, edit, approve, discard, regenerate.

Every handler here operates only on this application's own ``draft_replies``
table. None of them call the Gmail API to send anything or create a Gmail
draft -- ``approve``/``discard`` are pure status bookkeeping, and
``regenerate`` only overwrites this row's own subject/body/tone via Claude.
There is no send endpoint in this codebase; a draft can only ever be
inspected, edited, approved, discarded, or regenerated by a human.
"""

from __future__ import annotations

import uuid
from typing import Annotated, cast

from fastapi import APIRouter, Depends, Query, status

from app.agents import prompts
from app.agents.embeddings import HashingEmbeddingProvider
from app.agents.memory_retrieval import MemoryRetrievalService
from app.agents.schemas import ReplyDraftResult
from app.api.deps import (
    CurrentUserDep,
    DraftReplyServiceDep,
    SessionDep,
    SettingsDep,
    StructuredLLMClientDep,
)
from app.core.exceptions import NotFoundError
from app.infra.models.draft_reply import DraftReply
from app.infra.repositories.email import EmailRepository
from app.infra.repositories.memory import MemoryRepository
from app.schemas.draft_reply import (
    DraftReplyEdit,
    DraftReplyRead,
    DraftReplyRegenerateRequest,
)
from app.services.memory import MemoryService

router = APIRouter(prefix="/draft-replies", tags=["draft-replies"])


async def _get_owned_draft(
    draft_id: uuid.UUID,
    user: CurrentUserDep,
    service: DraftReplyServiceDep,
) -> DraftReply:
    """Fetch a draft, scoped to the current user.

    Raises:
        NotFoundError: The draft doesn't exist, or belongs to another user
            (returning 404 rather than 403 either way, so a caller cannot
            distinguish "not yours" from "doesn't exist").
    """
    draft = await service.get(draft_id)
    if draft is None or draft.user_id != user.id:
        raise NotFoundError("No draft reply with this id was found.")
    return draft


OwnedDraftDep = Annotated[DraftReply, Depends(_get_owned_draft)]


@router.get("", response_model=list[DraftReplyRead], summary="List draft replies")
async def list_draft_replies(
    user: CurrentUserDep,
    service: DraftReplyServiceDep,
    status_filter: str | None = Query(default=None, alias="status"),
) -> list[DraftReplyRead]:
    """List the current user's draft replies, optionally filtered by status."""
    drafts = await service.list_by_user(user.id, status=status_filter)
    return [DraftReplyRead.model_validate(d) for d in drafts]


@router.get("/{draft_id}", response_model=DraftReplyRead, summary="Get one draft reply")
async def get_draft_reply(draft: OwnedDraftDep) -> DraftReplyRead:
    """Fetch a single draft reply by id."""
    return DraftReplyRead.model_validate(draft)


@router.patch(
    "/{draft_id}", response_model=DraftReplyRead, summary="Edit a draft reply"
)
async def edit_draft_reply(
    draft: OwnedDraftDep,
    body: DraftReplyEdit,
    service: DraftReplyServiceDep,
) -> DraftReplyRead:
    """Hand-edit a draft's subject/body. Everything here stays editable.

    Marks the draft as ``user``-generated: once a human has touched the
    wording, it no longer reflects solely what the AI produced.
    """
    updated = await service.edit(
        draft.id,
        subject=body.subject,
        body_text=body.body_text,
        body_html=body.body_html,
    )
    return DraftReplyRead.model_validate(cast(DraftReply, updated))


@router.post(
    "/{draft_id}/approve",
    response_model=DraftReplyRead,
    summary="Approve a draft reply",
)
async def approve_draft_reply(
    draft: OwnedDraftDep, service: DraftReplyServiceDep
) -> DraftReplyRead:
    """Mark a draft as approved. Does not send anything."""
    updated = await service.approve(draft.id)
    return DraftReplyRead.model_validate(cast(DraftReply, updated))


@router.post(
    "/{draft_id}/discard",
    response_model=DraftReplyRead,
    summary="Discard a draft reply",
)
async def discard_draft_reply(
    draft: OwnedDraftDep, service: DraftReplyServiceDep
) -> DraftReplyRead:
    """Mark a draft as discarded -- it will not be sent."""
    updated = await service.discard(draft.id)
    return DraftReplyRead.model_validate(cast(DraftReply, updated))


@router.post(
    "/{draft_id}/regenerate",
    response_model=DraftReplyRead,
    status_code=status.HTTP_200_OK,
    summary="Regenerate a draft reply, optionally with a specific tone",
)
async def regenerate_draft_reply(
    draft: OwnedDraftDep,
    body: DraftReplyRegenerateRequest,
    service: DraftReplyServiceDep,
    claude_client: StructuredLLMClientDep,
    session: SessionDep,
    settings: SettingsDep,
) -> DraftReplyRead:
    """Re-run the Draft Reply Engine for this email, overwriting this draft.

    An explicit ``tone`` in the request body is honored exactly -- the model
    is instructed not to second-guess it. Without one, the model infers the
    best-fitting tone itself, the same as the original generation. The
    result always resets ``status`` back to ``"draft"``: a regenerated draft
    needs review again even if the version it replaced was approved.
    """
    email_repo = EmailRepository(session)
    email = await email_repo.get(draft.email_id)
    if email is None:
        raise NotFoundError("The email this draft replies to no longer exists.")

    memory_repo = MemoryRepository(session)
    memory_service = MemoryService(memory_repo)
    embedding_provider = HashingEmbeddingProvider(
        dimensions=settings.memory.embedding_dimensions
    )
    memory_retrieval = MemoryRetrievalService(
        memory_repo,
        memory_service,
        embedding_provider,
        default_top_k=settings.memory.retrieval_top_k,
    )
    recalled = await memory_retrieval.retrieve(
        user_id=draft.user_id,
        from_address=email.from_address,
        query_text=f"{email.subject}\n{email.body_text or ''}",
    )

    context = prompts.email_context(
        subject=email.subject,
        from_address=email.from_address,
        to_address=email.to_addresses,
        body=email.body_text or "",
    )
    memory_context = MemoryRetrievalService.format_for_prompt(recalled)
    if memory_context:
        context = f"{context}\n\n{memory_context}"
    context += prompts.tone_override_line(body.tone)

    result: ReplyDraftResult = await claude_client.complete(
        system=prompts.REPLY_DRAFT_SYSTEM,
        user_message=context,
        response_model=ReplyDraftResult,
        tenant_id=draft.tenant_id,
        user_id=draft.user_id,
        ai_history_id=None,
        node_name="reply_draft_regenerate",
    )

    updated = await service.replace_generated_content(
        draft.id,
        subject=result.subject,
        body_text=result.body_text,
        tone=result.tone,
        reasoning=result.reasoning,
        confidence=result.confidence,
    )
    return DraftReplyRead.model_validate(cast(DraftReply, updated))
